1.0.25
YusufsDiscordbot/YusufIsmails-Discord-core pull request #5
Opened 2021-11-22 18:39 UTC by RealYusufIsmail

Added some new methods and fixed a lot of issues

2021-11-23 07:33 UTC, Zabuzard requested changes

2021-11-23 07:33 UTC, Zabuzard commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
Do not remove the attribution notice. Put it back on `retrieveCommandData()` before this is merged. You have 7 days to fix this.

2021-11-23 11:19 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
I Thought since i change the name i don't have to give credit since it is different. The reason for this is that you do not own CommandData so i can use it with a different name

2021-11-23 11:20 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
And that i have given you credit for Command Connecter.

2021-11-23 11:22 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
I also dont know why you dont believe i did not take it from you how can i prove this to you

2021-11-23 11:25 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
@Zabuzard This is all the proof i can give you https://github.com/YusufsDiscordbot/Yusuf-s-Moderation-Bot/blob/ea658866b8484ff7d65bf57714482088b7747604/src/main/java/net/yusuf/bot/slash_commands/Command.java

2021-11-23 11:28 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
If you approve of the removal of the credits please let me know

2021-11-23 12:32 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
I have added a notice.

2021-11-23 22:17 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/Command.java
> +    void onButtonClick(@NotNull ButtonClickEvent event);
Fixed

2021-11-24 09:53 UTC, RealYusufIsmail commented
Ready for review @nDZIB

2021-11-24 10:12 UTC, RealYusufIsmail commented
@Zabuzard Please check if there is anything you want me to change,

2021-11-24 11:14 UTC, Zabuzard commented
> @Zabuzard Please check if there is anything you want me to change,

Attribution-wise, I am fine.

2021-11-25 07:21 UTC, merged

2021-11-25 07:21 UTC, RealYusufIsmail commented
Released