Jda v5
YusufsDiscordbot/YusufIsmails-Discord-core pull request #8
Opened 2021-12-04 09:18 UTC by RealYusufIsmail

Update to v5
Fixed a lot issues such as now were member can be null

2021-12-04 22:13 UTC, RealYusufIsmail commented on jda5/build.gradle
>      implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.78'
ignore

2021-12-07 12:53 UTC, RealYusufIsmail commented on jda.basic/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.78'
ignore

2021-12-07 12:53 UTC, RealYusufIsmail commented on javacord/build.gradle
> +    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.0'
ignore

2021-12-07 12:53 UTC, RealYusufIsmail commented on javacord/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.77'
ignore

2021-12-07 12:55 UTC, RealYusufIsmail commented on javacord.basic/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.77'
ignore

2021-12-07 12:55 UTC, RealYusufIsmail commented on javacord.basic/build.gradle
> +    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.0'
ignore

2021-12-07 12:55 UTC, RealYusufIsmail commented on application.basic/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.78'
ignore

2021-12-07 12:55 UTC, RealYusufIsmail commented on javacord.basic/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.77'
ignore

2021-12-07 12:56 UTC, RealYusufIsmail commented on javacord.basic/build.gradle
> +    implementation group: 'org.javacord', name: 'javacord', version: '3.3.2'
ignore

2021-12-08 10:11 UTC, RealYusufIsmail commented on javacord/build.gradle
> +    implementation group: 'org.javacord', name: 'javacord', version: '3.3.2'
ignore

2021-12-08 10:12 UTC, RealYusufIsmail commented on javacord/build.gradle
> +    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.77'
ignore

2021-12-10 14:13 UTC, Zabuzard requested changes

2021-12-10 14:13 UTC, Zabuzard commented on jda5/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/interactions/Command.java
> -     *         and modified by Yusuf
Add it back.

2021-12-10 14:15 UTC, RealYusufIsmail commented on jda5/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/interactions/Command.java
> -     *         and modified by Yusuf
Its at the top

2021-12-10 16:47 UTC, Zabuzard commented on jda5/src/main/java/io/github/yusufsdiscordbot/yusufsdiscordcore/bot/slash_command/interactions/Command.java
> -     *         and modified by Yusuf
Okay.

2021-12-15 17:38 UTC, merged